[package]
name = "core-utils"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cat"
path = "src/cat.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
